import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/context/provider";
import SidebarProvider from "@/components/sidebar/SidebarProvider"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lapor Mas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-100 ${inter.className} overflow-hidden`}>
        <Provider>
          <SidebarProvider>
          {children}
          </SidebarProvider>
        </Provider>
      </body>
    </html>
  )
}
